### PR TITLE
Enable Boost atomic for libfork

### PR DESCRIPTION
**Pull request by ConorWilliams**
Nice work on TMC @tzcnt, I wanted to reproduce your benchmarks, before making any changes I measured:

| Runtime | [libfork](https://github.com/ConorWilliams/libfork) | [TooManyCooks](https://github.com/tzcnt/TooManyCooks) | [concurrencpp](https://github.com/David-Haim/concurrencpp) |
| --- | --- | --- | --- |
| Mean Ratio to Best<br>(lower is better) | 1.00x | 1.23x | 101.92x |
| fib(35) | 40951 us | 56524 us | 5106416 us |
| fib(40) | 375238 us | 466106 us | 54286115 us |
| skynet (first run) | 4548 us | 5739 us | 197476 us |
| skynet (last run) | 2054 us | 2120 us | 194946 us |

This PR adds Boost via CPM.cmake which libfork uses to further optimize some atomic operations. With this change I measure:

| Runtime | [libfork](https://github.com/ConorWilliams/libfork) | [TooManyCooks](https://github.com/tzcnt/TooManyCooks) | [concurrencpp](https://github.com/David-Haim/concurrencpp) |
| --- | --- | --- | --- |
| Mean Ratio to Best<br>(lower is better) | 1.00x | 2.13x | 141.36x |
| fib(35) | 27196 us | 61907 us | 4979572 us |
| fib(40) | 237295 us | 522692 us | 45134632 us |
| skynet (first run) | 2966 us | 6296 us | 182739 us |
| skynet (last run) | 1442 us | 2771 us | 188189 us |

After that I tried increasing the iteration count to 5 because I thought it may just me measuring start-up costs:

| Runtime | [libfork](https://github.com/ConorWilliams/libfork) | [TooManyCooks](https://github.com/tzcnt/TooManyCooks) | [concurrencpp](https://github.com/David-Haim/concurrencpp) |
| --- | --- | --- | --- |
| Mean Ratio to Best<br>(lower is better) | 1.00x | 1.93x | 173.87x |
| fib(35) | 114506 us | 248406 us | 24453129 us |
| fib(40) | 1153398 us | 2405182 us | 264214943 us |
| skynet (first run) | 10900 us | 18439 us | 920160 us |
| skynet (last run) | 5878 us | 10389 us | 990099 us |

Then excluding concurrencppas because it was taking too long I tried 100 iterations:

| Runtime | [libfork](https://github.com/ConorWilliams/libfork) | [TooManyCooks](https://github.com/tzcnt/TooManyCooks) |
| --- | --- | --- |
| Mean Ratio to Best<br>(lower is better) | 1.00x | 2.02x |
| fib(35) | 2030602 us | 4143195 us |
| fib(40) | 20100414 us | 44703982 us |
| skynet (first run) | 109094 us | 209574 us |
| skynet (last run) | 105766 us | 199429 us |

Now I think the variation observed in the last three runs is just due to lack of averaging/standard error. 

Any ideas why I could be observing such different results from you? 

I compiled the benchmarks with clang version 18.0.0 (git@github.com:llvm/llvm-project.git 8a9bbac6629686bd1107cc0742b343a67d37a3c9) and ran with 32 threads on this:

```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 57 bits virtual
CPU(s):                          64
On-line CPU(s) list:             0-63
Thread(s) per core:              2
Core(s) per socket:              16
Socket(s):                       2
NUMA node(s):                    2
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           106
Model name:                      Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz
Stepping:                        6
CPU MHz:                         2900.002
BogoMIPS:                        4800.00
Virtualisation:                  VT-x
L1d cache:                       1.5 MiB
L1i cache:                       1 MiB
L2 cache:                        40 MiB
L3 cache:                        48 MiB
NUMA node0 CPU(s):               0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
NUMA node1 CPU(s):               1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe sys
                                 call nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni p
                                 clmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc
                                 _deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibp
                                 b stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm
                                  rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsav
                                 ec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku os
                                 pke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_
                                 capabilities
```

### CODE REVIEW

**Comment by ConorWilliams** [comment]
Trying on my (intel) laptop  with two threads I get:

| Runtime | [libfork](https://github.com/ConorWilliams/libfork) | [TooManyCooks](https://github.com/tzcnt/TooManyCooks) |
| --- | --- | --- |
| Mean Ratio to Best<br>(lower is better) | 1.00x | 1.89x |
| fib(35) | 276497 us | 602425 us |
| fib(40) | 3464875 us | 6960515 us |
| fib(45) | 40747333 us | 73245619 us |
| skynet (first run) | 13316 us | 23102 us |
| skynet (last run) | 14099 us | 24694 us |

**Comment by tzcnt** [comment]
Here is a fresh run on my server with your fork, before installing Boost:
| Runtime | [TooManyCooks](https://github.com/tzcnt/TooManyCooks) | [libfork](https://github.com/ConorWilliams/libfork) |
| --- | --- | --- |
| Mean Ratio to Best<br>(lower is better) | 1.13x | 1.30x |
| fib(35) | 23311 us | 30152 us |
| fib(40) | 165115 us | 211723 us |
| fib(45) | 1717989 us | 2178953 us |
| skynet (first run) | 3440 us | 2110 us |
| skynet (last run) | 1115 us | 1874 us |

And one after installing boost (1.85 from source since Debian doesn't provide a sufficiently up-to-date package):
| Runtime | [libfork](https://github.com/ConorWilliams/libfork) | [TooManyCooks](https://github.com/tzcnt/TooManyCooks) |
| --- | --- | --- |
| Mean Ratio to Best<br>(lower is better) | 1.00x | 1.49x |
| fib(35) | 21365 us | 25691 us |
| fib(40) | 138146 us | 164188 us |
| fib(45) | 1418221 us | 1716413 us |
| skynet (first run) | 1212 us | 3407 us |
| skynet (last run) | 1089 us | 1130 us |

So that's a nice win

**Comment by ConorWilliams** [comment]
I have integrated a few of the benchmarks (fib/integrate) from [your old libfork fork](https://github.com/tzcnt/libfork/tree/add_tmc) into the [latest version of libfork](https://github.com/ConorWilliams/libfork/tree/tmc) because I wanted to see if using Google benchmark would make a difference (with averaging and warmup runs). Not a great deal of difference but thought I'd post here, this was me running `./build/dev/bench/benchmark --benchmark_time_unit=ms --benchmark_repetitions=5 --benchmark_report_aggregates_only=true --benchmark_filter="(fib|integ).*(libfork<lazy_pool, numa_strategy::seq|tmc)"` on the same 32 core machine:

```
Run on (64 X 800 MHz CPU s)
CPU Caches:
  L1 Data 48 KiB (x32)
  L1 Instruction 32 KiB (x32)
  L2 Unified 1280 KiB (x32)
  L3 Unified 24576 KiB (x2)
Load Average: 5.08, 5.66, 5.95
-------------------------------------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------------------------
fib_libfork/1/real_time_median             13168 ms        0.113 ms            5 fib(n)=42 green_threads=1
fib_libfork/2/real_time_median              6392 ms        0.135 ms            5 fib(n)=42 green_threads=2
fib_libfork/4/real_time_median              3272 ms        0.091 ms            5 fib(n)=42 green_threads=4
fib_libfork/8/real_time_median              1689 ms        0.069 ms            5 fib(n)=42 green_threads=8
fib_libfork/16/real_time_median              904 ms        0.061 ms            5 fib(n)=42 green_threads=16
fib_libfork/24/real_time_median              653 ms        0.049 ms            5 fib(n)=42 green_threads=24
fib_libfork/32/real_time_median              525 ms        0.040 ms            5 fib(n)=42 green_threads=32

fib_tmc/1/real_time_median                 26484 ms        0.067 ms            5 fib(n)=42 green_threads=1
fib_tmc/2/real_time_median                 13811 ms        0.129 ms            5 fib(n)=42 green_threads=2
fib_tmc/4/real_time_median                  7163 ms        0.128 ms            5 fib(n)=42 green_threads=4
fib_tmc/8/real_time_median                  3675 ms        0.065 ms            5 fib(n)=42 green_threads=8
fib_tmc/16/real_time_median                 2034 ms        0.053 ms            5 fib(n)=42 green_threads=16
fib_tmc/24/real_time_median                 1369 ms        0.123 ms            5 fib(n)=42 green_threads=24
fib_tmc/32/real_time_median                 1232 ms        0.044 ms            5 fib(n)=42 green_threads=32

integrate_libfork/1/real_time_median        9298 ms        0.082 ms            5 green_threads=1 integrate_epsilon=1n integrate_n=10k
integrate_libfork/2/real_time_median        4747 ms        0.063 ms            5 green_threads=2 integrate_epsilon=1n integrate_n=10k
integrate_libfork/4/real_time_median        2379 ms        0.064 ms            5 green_threads=4 integrate_epsilon=1n integrate_n=10k
integrate_libfork/8/real_time_median        1242 ms        0.051 ms            5 green_threads=8 integrate_epsilon=1n integrate_n=10k
integrate_libfork/16/real_time_median        698 ms        0.038 ms            5 green_threads=16 integrate_epsilon=1n integrate_n=10k
integrate_libfork/24/real_time_median        481 ms        0.035 ms            5 green_threads=24 integrate_epsilon=1n integrate_n=10k
integrate_libfork/32/real_time_median        381 ms        0.046 ms            5 green_threads=32 integrate_epsilon=1n integrate_n=10k

integrate_tmc/1/real_time_median           17471 ms        0.123 ms            5 green_threads=1 integrate_epsilon=1n integrate_n=10k
integrate_tmc/2/real_time_median            8928 ms        0.138 ms            5 green_threads=2 integrate_epsilon=1n integrate_n=10k
integrate_tmc/4/real_time_median            4626 ms        0.140 ms            5 green_threads=4 integrate_epsilon=1n integrate_n=10k
integrate_tmc/8/real_time_median            2327 ms        0.139 ms            5 green_threads=8 integrate_epsilon=1n integrate_n=10k
integrate_tmc/16/real_time_median           1332 ms        0.032 ms            5 green_threads=16 integrate_epsilon=1n integrate_n=10k
integrate_tmc/24/real_time_median            889 ms        0.025 ms            5 green_threads=24 integrate_epsilon=1n integrate_n=10k
integrate_tmc/32/real_time_median            766 ms        0.025 ms            5 green_threads=32 integrate_epsilon=1n integrate_n=10k
```

Digging into TMC it seems that every task is triggering a heap allocation; the factor of 2 slow down vs libfork is consistent with my experience moving to a cactus stack (which almost never allocates). I expect on the `matmul` benchmark they would come much closer (assuming TMC is also a continuation stealer?).

**Comment by ConorWilliams** [comment]
I wonder if the Pre boost difference was due to the allocator! My system was finding `Using malloc: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2` what about yours?

**Comment by ConorWilliams** [comment]
As expected on `matmul` similar performace:

```
Run on (64 X 800 MHz CPU s)
CPU Caches:
  L1 Data 48 KiB (x32)
  L1 Instruction 32 KiB (x32)
  L2 Unified 1280 KiB (x32)
  L3 Unified 24576 KiB (x2)
Load Average: 5.66, 5.43, 5.97
----------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                  Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------------------------------------------------------
matmul_libfork/1/real_time_median        6060 ms        0.111 ms            5 green_threads=1 mat NxN=2.048k
matmul_libfork/2/real_time_median        3072 ms        0.161 ms            5 green_threads=2 mat NxN=2.048k
matmul_libfork/4/real_time_median        1576 ms        0.158 ms            5 green_threads=4 mat NxN=2.048k
matmul_libfork/8/real_time_median         845 ms        0.086 ms            5 green_threads=8 mat NxN=2.048k
matmul_libfork/16/real_time_median        446 ms        0.036 ms            5 green_threads=16 mat NxN=2.048k
matmul_libfork/24/real_time_median        307 ms        0.040 ms            5 green_threads=24 mat NxN=2.048k
matmul_libfork/32/real_time_median        254 ms        0.051 ms            5 green_threads=32 mat NxN=2.048k

matmul_tmc/1/real_time_median            6235 ms        0.128 ms            5 green_threads=1 mat NxN=2.048k
matmul_tmc/2/real_time_median            3235 ms        0.126 ms            5 green_threads=2 mat NxN=2.048k
matmul_tmc/4/real_time_median            1637 ms        0.158 ms            5 green_threads=4 mat NxN=2.048k
matmul_tmc/8/real_time_median             863 ms        0.110 ms            5 green_threads=8 mat NxN=2.048k
matmul_tmc/16/real_time_median            467 ms        0.036 ms            5 green_threads=16 mat NxN=2.048k
matmul_tmc/24/real_time_median            336 ms        0.039 ms            5 green_threads=24 mat NxN=2.048k
matmul_tmc/32/real_time_median            312 ms        0.034 ms            5 green_threads=32 mat NxN=2.048k
```

**Comment by tzcnt** [comment]
I definitely want to give all libraries a fair shake in these benchmarks, so I'd be happy to accept any tweaks to these implementations.

I surely expect libfork to be faster, since it uses a cactus stack. Since I first compared our libraries side-by-side (with that original fork), I think our design goals have diverged somewhat. My goal is to create a general-purpose library, with a super clean API, that has the maximum performance possible within those constraints. This means I can't do strict cactus stack, because I lose the ability to spawn detached tasks. And I'm unsure how a cactus stack would work when handing off a task to an external executor.

I'm also unwilling to pursue anything that requires users to mangle their function declarations, because I want to provide a simple upgrade path from existing code - just change the return type to tmc::task<return_type> and add co_await at the call site. `task<size_t> fib(size_t n)`. I had experimented with some bulk allocation strategies for child tasks (you could consider this a "partial" cactus stack - for skynet it reduces the number of allocations by 10x) but that also required modifying the function declarations, and didn't yield substantial performance gains, so I put it on the back burner. Due to the limited introspection capabilities given to us by the 

I found that just using a better system allocator reduced the allocation overhead substantially... and considered this "good enough for now" as I switch modes into cleaning things up for an initial release. On my machine it is using tcmalloc as I found that gives the best performance. Earlier versions of the lib performed better with jemalloc, AFAIK because it handles memory fragmentation better, but with the latest design, this is less of an issue.

On the subject of benchmarking, I also came to the realization that the typical benchmark advice (warmup period, disable CPU boost, performance scheduler) doesn't apply well to what I'm testing here - there are a lot of things that a runtime could do that might affect CPU boost negatively (either spin waiting OR mutex blocking), as well as how long it takes to wake up and sleep threads. A fast runtime will also complete the wakeup loops more quickly, and since the ratio of real work to overhead is better, it will heat up the CPU more in a shorter timeframe; on a laptop this will result in throttling. So following the typical benchmark advice gives unfair advantages to inefficient runtimes. A real user runs the program once from a cold start.

To beat a dead horse: another thing that happens when you run multiple benchmarks back to back on a hot executor is that the threads don't fully go to sleep between runs, so they will already be in the work stealing loop when new tasks start appearing from the next benchmark iteration. I think that this is something that could happen both with my and your executor (due to `k_min_steal_attempts =1024`?) and again, punishes a theoretical "ideal" executor that could perfectly complete all of its tasks and instantaneously sleep all of its threads before the next iteration starts. The simplest way to isolate this is just to run the benchmark once.

I might use a microbenchmarking approach when it comes to testing a small performance improvement between different commits on my library where I need 1% accuracy, but for a cross-cutting comparison like this, the differences should be sufficiently clear with just a program. I also don't care to try to create apples-to-apples microbenchmarks with applications written in other programming languages, and I want to make it easy for anyone to download this repo and run it for themselves. So whole program benchmarks it is.

I'd be interested in talking with you about your use of hwloc - I think we are doing something similar, but not quite, with the numa neighbors being preferential steal targets... and pick your brain on how I could implement a bump-allocation strategy that's transparent to the user. Feel free to message me on the cpplang slack @tzcnt

**Comment by tzcnt** [comment]
IIRC from my benchmarks the memory allocation was only around 20-30% of the overhead - I need to take some time to compare the perf traces of our libs.

On the subject of hwloc, our test machines are somewhat fundamentally different - yours is 2 CPUs, each with 16 cores, but those 16 cores all share an L3 cache and AFAIK have equivalent latency to each other. So there are only 2 latency domains (the 2 NUMA nodes).

I'm using a 64 core EPYC 7742. Although I have mine configured as a single NUMA node, the physical chiplet archictecture results in 16 groups of 4 cores that each share a smaller amount of L3 cache. This can be considered a NUCA (non-uniform cache architecture) with multiple tiers of increasing latency domains. You can see this in [this visualization](https://images.anandtech.com/doci/16315/Bounce-7742.png) from Anandtech.

So while libfork is optimized for the different NUMA nodes (by grouping threads according to NUMA nodes), TooManyCooks is optimized for the NUCA structure (by grouping threads according to L3 caches). This may explain the *relatively* better performance on my machine using my lib.

**Comment by tzcnt** [comment]
I pushed an update that includes the results with Boost for libfork, but I'm reluctant to accept this PR as-is... adding the entire boost.xz as a dependency seems a bit heavy. I'd accept any of the following:
- a vendored Boost or reimplemented version. IIUC you're only using it for LF_ATOMIC_THREAD_FENCE_SEQ_CST which generates a couple of assembly instructions, and I think dropping this dependency would make your users happy as well.
- a FindBoost script. Your choice as to whether it would fatal error, or simply warn, on failing to find Boost.

**Comment by ConorWilliams** [comment]
Hi @tzcnt many thanks for your detailed responses on this, I'll try and respond to everything:

> I surely expect libfork to be faster, since it uses a cactus stack. Since I first compared our libraries side-by-side (with that original fork), I think our design goals have diverged somewhat. My goal is to create a general-purpose library, with a super clean API, that has the maximum performance possible within those constraints. This means I can't do strict cactus stack, because I lose the ability to spawn detached tasks. And I'm unsure how a cactus stack would work when handing off a task to an external executor.

I agree with your goal, detached tasks are defiantly not possible with with a cactus stack. I believe, as long as the external executor was cactus-stack aware, then you could hand-off to it using the explicit scheduling API.

> I'm also unwilling to pursue anything that requires users to mangle their function declarations, because I want to provide a simple upgrade path from existing code - just change the return type to tmc::task<return_type> and add co_await at the call site. task<size_t> fib(size_t n). 

Fair enough, I too would like to remove the need for templated declarations. However, I am quite happy to keep the requirement of a modified first argument as the users API/ABI changes when they move from `T -> task<T>` anyway and the standard library uses this API for allocators.

> I found that just using a better system allocator reduced the allocation overhead substantially... and considered this "good enough for now" as I switch modes into cleaning things up for an initial release. On my machine it is using tcmalloc as I found that gives the best performance. Earlier versions of the lib performed better with jemalloc, AFAIK because it handles memory fragmentation better, but with the latest design, this is less of an issue.

I'll try and test with `tcmalloc`.

> On the subject of benchmarking, I also came to the realization that the typical benchmark advice (warmup period, disable CPU boost, performance scheduler) doesn't apply well to what I'm testing here - there are a lot of things that a runtime could do that might affect CPU boost negatively (either spin waiting OR mutex blocking), as well as how long it takes to wake up and sleep threads. A fast runtime will also complete the wakeup loops more quickly, and since the ratio of real work to overhead is better, it will heat up the CPU more in a shorter timeframe; on a laptop this will result in throttling. So following the typical benchmark advice gives unfair advantages to inefficient runtimes. A real user runs the program once from a cold start.

Whilst I agree with some of this I think repeating and averaging is important for good statistics.

> To beat a dead horse: another thing that happens when you run multiple benchmarks back to back on a hot executor is that the threads don't fully go to sleep between runs, so they will already be in the work stealing loop when new tasks start appearing from the next benchmark iteration. I think that this is something that could happen both with my and your executor (due to k_min_steal_attempts =1024?) and again, punishes a theoretical "ideal" executor that could perfectly complete all of its tasks and instantaneously sleep all of its threads before the next iteration starts. The simplest way to isolate this is just to run the benchmark once.

This can indeed happen with my thread pool.

> I'd be interested in talking with you about your use of hwloc - I think we are doing something similar, but not quite, with the numa neighbors being preferential steal targets... and pick your brain on how I could implement a bump-allocation strategy that's transparent to the user. Feel free to message me on the cpplang slack @tzcnt

I've got a detailed breakdown of how I use hwloc in the paper, I'll reach out to you on slack :) 

> IIRC from my benchmarks the memory allocation was only around 20-30% of the overhead - I need to take some time to compare the perf traces of our libs.

I'd be interested to see these results.

> On the subject of hwloc, our test machines are somewhat fundamentally different - yours is 2 CPUs, each with 16 cores, but those 16 cores all share an L3 cache and AFAIK have equivalent latency to each other. So there are only 2 latency domains (the 2 NUMA nodes). I'm using a 64 core EPYC 7742. Although I have mine configured as a single NUMA node, the physical chiplet architecture results in 16 groups of 4 cores that each share a smaller amount of L3 cache. This can be considered a NUCA (non-uniform cache architecture) with multiple tiers of increasing latency domains. You can see this in [this visualization](https://images.anandtech.com/doci/16315/Bounce-7742.png) from Anandtech. So while libfork is optimized for the different NUMA nodes (by grouping threads according to NUMA nodes), TooManyCooks is optimized for the NUCA structure (by grouping threads according to L3 caches). This may explain the relatively better performance on my machine using my lib.

This is very interesting, I'd be interested in seeing the output of `lstopo` on this machine. I believe that libfork should still optimize for this topology when using the greedy scheduler and `fan` distribution strategy but, I need a new strategy to handle this for lazy.

> I pushed an update that includes the results with Boost for libfork, but I'm reluctant to accept this PR as-is... adding the entire boost.xz as a dependency seems a bit heavy. I'd accept any of the following:
> - A vendored Boost or reimplemented version. IIUC you're only using it for LF_ATOMIC_THREAD_FENCE_SEQ_CST which generates a couple of assembly instructions, and I think dropping this dependency would make your users happy as well.
> - A FindBoost script. Your choice as to whether it would fatal error, or simply warn, on failing to find Boost.

Adding `boost.atomic` as a dependency to a benchmark suit seems natural to me, eventually you will have lots of libs here. The compile time on my laptop for `boost.atomic` is ~45 seconds which seems very moderate. I would like to remove the `boost.atomic` dependency but boost atomic is implemented in assembly and it seems like too much duplication for what is actually a fairly lightweight dependency.  

If I cannot convince you to accept pulling in `boost.atomic` then I will go with option 2 and fail on compilation without boost. Let me know :)

**Comment by tzcnt** [comment]
I have marked boost as required with the same version you use in libfork (1.83.0)... also I have decided to go with a single warmup run before the timed run since there are certain structures that may be lazy initialized.

**Pull request closed without merging**
